### PR TITLE
Improve watchdog reliability. Add panic button driver. Simplify some code repetition 

### PR DESCRIPTION
**Pull request by cmorse**
This should improve how reliable the watchdog checking is. I've had many times where the websocket would be disconnected, but the watchdog would not catch it. I updated the watchdog so that it is based on the last time that a msg was received from the websocket, rather than the last time that 'refresh()` was called

I've been using this code for 3-4 months and the new watchdog code has reliably recovered the websocket connection many times.

### CODE REVIEW

**Comment by samyun** [comment]
@cmorse planning on checking this in?

**Comment by cmorse** [comment]
I don't have write access to this repo

**Comment by jedbro** [comment]
@cmorse  - Do we know who has write access?
I'd like to get this checked in and add support for additional new Ring devices.

**Comment by samyun** [comment]
@ardichoke has write access, looking at previous PRs in this project. 

@csteele-PD and @djdizzyd are both listed as org members of HubitatCommunity with recent activity - either of you have write access and can look at this and #18?

**Comment by Banner-Keith** [comment]
Sorry guys. I didn't get any notifications whatsoever about this. I just saw the tag tonight in the community thread. This looks good to me.

**Pull request merged**
