### PR TITLE
Support floodlight_pro (Floodlight Pro), update lpd_v2 = Pro 1, not Pro 2

### PR DESCRIPTION
**Pull request by samyun**

### CODE REVIEW

**Comment by samyun** [comment]
Fixes #17

**Comment by Banner-Keith** [comment]
Do we have someone with the lpd-v2 that can verify that this change works? My doorbell is the lpd-v1.

**Comment by Banner-Keith** [comment]
Nevermind. Mine is actually lpd_v2. This looks good.

**Comment by samyun** [comment]
I was about to say, I've been using it on my lpd-v2 and it works correctly :)

**Pull request merged**
